# Generated by Django 5.0.2 on 2024-02-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UsersModel',
        ),
    ]
